---

# roles/example/tasks/main.yml
#- name: added in 2.4, previouslly you used 'include'
#  import_tasks: redhat.yml
#  when: ansible_os_platform|lower == 'redhat'
#- import_tasks: debian.yml
#  when: ansible_os_platform|lower == 'debian'

- name: "Install Windows updates."
  win_updates:
    category_names: "{{ win_updates_category_names }}"
  register: win_updates_result
  failed_when: win_updates_result.failed is defined and win_updates_result.failed and win_updates_reboot == False


